version: '3.8'

services:
  db:
    image: postgres:16
    container_name: personal_planner_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: personalplanner1509
      POSTGRES_DB: personal_planner_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
